apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: config-history-operator-serving-cert
  labels:
    app: config-history-operator
  name: gitserver
  namespace: config-history-operator
spec:
  ports:
    - name: http # TODO: Make this https
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: config-history-operator
  sessionAffinity: None
  type: ClusterIP
