apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: config-history-operator-serving-cert
  labels:
    app: config-history-operator
  name: metrics
  namespace: config-history-operator
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: config-history-operator
  sessionAffinity: None
  type: ClusterIP
