apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:config-history-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin # TODO: This should be cluster-viewer
subjects:
  - kind: ServiceAccount
    namespace: config-history-operator
    name: config-history-operator